name       : python-wurlitzer
version    : 1.0.1
release    : 1
source     :
    - https://github.com/minrk/wurlitzer/archive/1.0.1.tar.gz : d31c4a1a36ae2bf3c648ad8513bcd473d344002de80933f78d8ddfedb6076ee8
license    : MIT
component  : programming.python
summary    : Capture C-level stdout/stderr in Python
description: |
    Capture C-level stdout/stderr pipes in Python via os.dup2.
builddeps  :
    - python-setuptools
    - python-mock
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test test.py
    %python3_test test.py

