name       : python-wurlitzer
version    : 3.0.3
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/w/wurlitzer/wurlitzer-3.0.3.tar.gz : 224f5fe70618be3872c05dfddc8c457191ec1870654596279fcc1edadebe3e5b
homepage   : https://github.com/minrk/wurlitzer
license    : MIT
component  : programming.python
summary    : Capture C-level stdout/stderr in Python
description: |
    Capture C-level stdout/stderr pipes in Python via os.dup2.
builddeps  :
    - python-mock
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 test.py

