name       : python-wurlitzer
version    : 2.0.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/w/wurlitzer/wurlitzer-2.0.1.tar.gz : d08f0728a998441aac3d7a0f8cd6dfed2ba2525144878fb49599b719085b7543
homepage   : https://github.com/minrk/wurlitzer
license    : MIT
component  : programming.python
summary    : Capture C-level stdout/stderr in Python
description: |
    Capture C-level stdout/stderr pipes in Python via os.dup2.
builddeps  :
    - python-mock
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 test.py

